SELECT "LASTNAME", "FIRSTNAME" from EMPLOYEE 
 WHERE
   EMPID = '33371';
      
 SELECT "LASTNAME", "FIRSTNAME" from EMPLOYEE 
 WHERE
   EMPID = '52421';
   
 SELECT "EMPID" from EARNINGS
 WHERE
   REGEARNINGS > '25' and 
   PAYWEEKENDDATE = '30-MAY-03';
   
 SELECT  "LASTNAME", "FIRSTNAME" FROM EMPLOYEE
WHERE STREET LIKE '__8_6%';

SELECT AVG(INCOMETAX )
FROM Deductions
WHERE PAYWEEKENDDATE = '23-MAY-03';

SELECT COUNT(EMPID)
FROM EMPLOYEE;

SELECT SUM (EI), SUM (CPP)
FROM DEDUCTIONS
WHERE PAYWEEKENDDATE = '30-MAY-03';

SELECT "EMPID" from DEDUCTIONS
 WHERE
   INCOMETAX IS NULL;
 
 SELECT SUM(REGHOURS +  OTIMEHOURS)
FROM TIMESHEET
WHERE PAYWEEKENDDATE = '23-MAY-03';  

SELECT DISTINCT "CITY" from EMPLOYEE;

SELECT LASTNAME, COALESCE(STREET, 'Not available') as address from EMPLOYEE
ORDER BY LASTNAME ASC; 

SELECT "LASTNAME", "FIRSTNAME", To_Char ((HIREDATE), 'fmMonth ddth, yyyy')
FROM EMPLOYEE
WHERE HIREDATE BETWEEN '01-JAN-02' AND '31-DEC-02';

SELECT "LASTNAME", "FIRSTNAME", To_Char ((HIREDATE), 'fmMonth ddth, yyyy')
FROM EMPLOYEE
WHERE HIREDATE >= '01-JAN-02' 
  AND HIREDATE <= '31-DEC-02';
 
 Select JOBCODE, DESCRIPTION, PAYRATE, PAYTYPE, (PAYRATE * 1.08) as "PAYRATE INCREASE" from JOB;
 
SELECT MAX(OTIMEHOURS)
FROM TIMESHEET
WHERE PAYWEEKENDDATE = '30-MAY-03';
   