--QUESTIOPN 1
SELECT LASTNAME, FIRSTNAME, CITY
FROM EMPLOYEE
WHERE JOBCODE = ANY (SELECT JOBCODE FROM JOB WHERE DESCRIPTION = 'Cashier')
ORDER BY CITY ASC;

SELECT EMPLOYEE.LASTNAME, EMPLOYEE.FIRSTNAME, EMPLOYEE.CITY
From EMPLOYEE INNER JOIN JOB ON JOB.JOBCODE = EMPLOYEE.JOBCODE
WHERE DESCRIPTION = 'Cashier'; 

--QUESTIOPN 2
SELECT SUM (REGEARNINGS + OTIMEEARNINGS)
FROM EARNINGS
WHERE EMPID = ANY (SELECT EMPID FROM EMPLOYEE WHERE FIRSTNAME = 'Ashley')
AND PAYWEEKENDDATE = '30-MAY-03';


--QUESTIOPN 3
SELECT SIN, EMPID
FROM EMPLOYEE
WHERE EMPID = ANY (SELECT EMPID FROM DEDUCTIONS WHERE PAYWEEKENDDATE = '23-MAY-03' AND INCOMETAX > '150');

--QUESTIOPN 4
SELECT DISTINCT LASTNAME, FIRSTNAME
FROM EMPLOYEE
WHERE EMPID = ANY (SELECT EMPID FROM EARNINGS WHERE REGEARNINGS >'0' OR OTIMEEARNINGS >'0' );

--QUESTIOPN 5
SELECT DESCRIPTION FROM JOB 
WHERE JOBCODE = ANY (SELECT JOBCODE FROM EMPLOYEE WHERE EMPID = ANY
(SELECT EMPID FROM DEDUCTIONS WHERE PAYWEEKENDDATE = '23 May 2003' AND PENSIONPLAN > 10));

--QUESTIOPN 6
SELECT DISTINCT LASTNAME, FIRSTNAME
FROM EMPLOYEE
WHERE EMPID = ANY (SELECT EMPID FROM DEDUCTIONS WHERE PAYWEEKENDDATE = '23-MAY-03' AND INCOMETAX IS NULL);

--QUESTIOPN 7
SELECT EMPLOYEE.LASTNAME, EMPLOYEE.FIRSTNAME, ((EARNINGS.REGEARNINGS+ EARNINGS.OTIMEEARNINGS) - (DEDUCTIONS.EI+DEDUCTIONS.CPP+DEDUCTIONS.UNIONDUES+DEDUCTIONS.PENSIONPLAN+ DEDUCTIONS.INCOMETAX))AS NetPay
From EARNINGS INNER JOIN EMPLOYEE ON EMPLOYEE.EMPID =EARNINGS.EMPID
INNER JOIN DEDUCTIONS ON DEDUCTIONS.EMPID =EMPLOYEE.EMPID
AND DEDUCTIONS.PAYWEEKENDDATE = EARNINGS.PAYWEEKENDDATE
WHERE EARNINGS.PAYWEEKENDDATE = '30-MAY-03'; 

--QUESTIOPN 8
SELECT EMPLOYEE.LASTNAME, EMPLOYEE.FIRSTNAME, TIMESHEET.PAYWEEKENDDATE, TIMESHEET.REGHOURS
From TIMESHEET INNER JOIN EMPLOYEE ON EMPLOYEE.EMPID = TIMESHEET.EMPID
ORDER BY EMPLOYEE.LASTNAME ASC;

--QUESTIOPN 9
SELECT EMPLOYEE.LASTNAME, EMPLOYEE.FIRSTNAME, TIMESHEET.PAYWEEKENDDATE, TIMESHEET.REGHOURS
From TIMESHEET RIGHT JOIN EMPLOYEE ON EMPLOYEE.EMPID = TIMESHEET.EMPID
ORDER BY EMPLOYEE.LASTNAME ASC;

DROP VIEW RegEarningsVU; 
--QUESTIOPN 10
CREATE VIEW RegEarningsVU AS
SELECT EMPID, PAYWEEKENDDATE, REGEARNINGS
FROM EARNINGS;

--QUESTIOPN 11
select * from RegEarningsVU;
INSERT INTO TIMESHEET 
VALUES('72201','23-May-03','40.00','10.00');
INSERT INTO EARNINGS VALUES (72201,'23-May-03',5000,0);
select * from RegEarningsVU;
select * from EARNINGS;

--Explain your answer.
--Yes, the change was notice in the RegEarningsVU view because view table contains rows and columns, just like a real table so it will show shows up-to-date data.

DROP VIEW PayrollMay30VU; 
--QUESTIOPN 13
CREATE VIEW PayrollMay30VU 
AS SELECT EARNINGS.Empid as "Employe ID", EARNINGS.Regearnings as "Regular Earnings", EARNINGS.Otimeearnings as "Overtime Earnings", 
(DEDUCTIONS.EI+DEDUCTIONS.CPP+DEDUCTIONS.UNIONDUES+DEDUCTIONS.PENSIONPLAN+DEDUCTIONS.INCOMETAX) AS "Total Deductions"
FROM EARNINGS, DEDUCTIONS
WHERE DEDUCTIONS.EMPID =EARNINGS.EMPID
AND DEDUCTIONS.PAYWEEKENDDATE = EARNINGS.PAYWEEKENDDATE;

select * from PayrollMay30VU;

--QUESTIOPN 14
UPDATE Employee 
SET 
    Province = 'BC'
WHERE
   CITY = 'Tuxford';

DROP VIEW NetPayMay30VU;

--QUESTIOPN 15
CREATE VIEW NetPayMay30VU 
AS SELECT EARNINGS.Empid as "Employe ID", (EARNINGS.Regearnings + EARNINGS.Otimeearnings) as "Total Earnings", 
(DEDUCTIONS.EI+DEDUCTIONS.CPP+DEDUCTIONS.UNIONDUES+DEDUCTIONS.PENSIONPLAN+DEDUCTIONS.INCOMETAX) AS "Total Deductions",
((EARNINGS.Regearnings + EARNINGS.Otimeearnings)-
(DEDUCTIONS.EI+DEDUCTIONS.CPP+DEDUCTIONS.UNIONDUES+DEDUCTIONS.PENSIONPLAN+DEDUCTIONS.INCOMETAX))AS "Net Pay"
FROM EARNINGS, DEDUCTIONS
WHERE DEDUCTIONS.EMPID =EARNINGS.EMPID
AND DEDUCTIONS.PAYWEEKENDDATE = EARNINGS.PAYWEEKENDDATE;


--QUESTIOPN 16
Describe NetPayMay30VU;
select * from NetPayMay30VU;

--QUESTIOPN 17
UPDATE Employee 
SET 
    Province = 'SK'
WHERE
   CITY = 'Tuxford';
   
select * from Employee;  

